apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-app
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
      - name: docker-app-ctr
        image: alpernbt/docker-app:latest
        ports:
        - containerPort: 3000

